import { useState } from 'react'

const request = async body => { const response = await fetch('/api/onboarding', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw Object.assign(new Error(result.error || '요청을 완료하지 못했습니다.'), { events: result.events || [] }); return result }
const eventText = events => events.some(item => item.type === 'files.written') ? '승인된 Wiki scaffold를 만들었습니다.' : events.some(item => item.type === 'approval.required') ? '아직 파일을 만들지 않았습니다. 내용을 검토하고 승인해 주세요.' : ''

function Preview({ preview, mode, onBack, onConfirm, busy, error }) { return <section className="onboarding-card" role="dialog" aria-modal="true" aria-labelledby="preview-title"><small>APPROVAL PREVIEW</small><h1 id="preview-title">승인 전 파일 계획</h1><p>서버가 allowlist 경로만 다시 렌더링합니다. 브라우저와 모델이 파일 경로를 정하지 않습니다.</p><div className="file-preview">{preview.files.map(file => <details key={file.path}><summary>{file.path}</summary><pre>{file.content}</pre></details>)}</div>{mode === 'read-only-demo' && <p className="onboarding-notice">이 배포 환경은 읽기 전용입니다. 내보내기 미리보기는 가능하지만 저장은 할 수 없습니다. 로컬 실행에서 저장하세요.</p>}{error && <p className="onboarding-error" role="alert">{error}</p>}<footer><button onClick={onBack} disabled={busy}>수정</button><button className="primary" onClick={onConfirm} disabled={busy || mode === 'read-only-demo'}>{busy ? '생성 중…' : '승인하고 생성'}</button></footer></section> }

export default function Onboarding({ serverState, onStateChange }) {
  const [statement, setStatement] = useState(''); const [clarifications, setClarifications] = useState([]); const [answer, setAnswer] = useState(''); const [analysis, setAnalysis] = useState(null); const [blueprintText, setBlueprintText] = useState(''); const [identity, setIdentity] = useState({ memberId: '', displayName: '', workingContext: '' }); const [preview, setPreview] = useState(null); const [events, setEvents] = useState([]); const [completedState, setCompletedState] = useState(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const analyze = async event => { event.preventDefault(); setBusy(true); setError(''); try { const result = await request({ action: 'analyze', statement, clarifications }); setAnalysis(result); setBlueprintText(JSON.stringify(result.blueprint, null, 2)); setEvents(result.events || []) } catch (failure) { setError(failure.message); setEvents(failure.events || []) } finally { setBusy(false) } }
  const askAgain = async event => { event.preventDefault(); if (!answer.trim() || clarifications.length >= 2) return; const nextClarifications = [...clarifications, answer]; setBusy(true); setError(''); try { const result = await request({ action: 'analyze', statement, clarifications: nextClarifications }); setClarifications(nextClarifications); setAnswer(''); setAnalysis(result); setBlueprintText(JSON.stringify(result.blueprint, null, 2)); setEvents(result.events || []) } catch (failure) { setError(failure.message); setEvents(failure.events || []) } finally { setBusy(false) } }
  const previewFiles = async event => { event.preventDefault(); setBusy(true); setError(''); try { const blueprint = JSON.parse(blueprintText); const result = await request({ action: 'preview-blueprint', blueprint, identity }); setPreview(result.preview); setEvents(result.events || []) } catch (failure) { setError(failure instanceof SyntaxError ? 'Blueprint JSON 형식을 확인해 주세요.' : failure.message); setEvents(failure.events || []) } finally { setBusy(false) } }
  const save = async () => { setBusy(true); setError(''); try { const result = await request({ action: 'save-blueprint', blueprint: JSON.parse(blueprintText), identity, expectedDigest: preview.digest }); setEvents(result.events || []); setCompletedState(result.state) } catch (failure) { setError(failure.message); setEvents(failure.events || []) } finally { setBusy(false) } }
  if (preview) return <Preview preview={preview} mode={serverState.persistenceMode} onBack={() => setPreview(null)} onConfirm={save} busy={busy} error={error} />
  if (events.some(item => item.type === 'files.written')) return <section className="onboarding-card onboarding-reward" role="status"><span className="reward-sprite" aria-hidden="true">✦</span><small>SESSION COMPLETED</small><h1>Wiki 길드홀이 준비됐어요!</h1><p>{eventText(events)}</p><button className="primary" autoFocus onClick={() => { onStateChange(completedState); window.location.reload() }}>마을로 들어가기</button></section>
  return <section className="onboarding-layer" aria-label="Knowledge Guild RPG 온보딩"><div className="onboarding-scene" aria-hidden="true"><i className="prologue-hall" /><i className="prologue-guide" /></div><form className="onboarding-card" onSubmit={analysis ? previewFiles : analyze}><small>PROJECT WIKI ARCHITECT</small><h1>{analysis ? '해석과 blueprint를 검토해 주세요' : '어떤 Wiki를 만들고 싶나요?'}</h1>{!analysis ? <><p>자유롭게 설명해 주세요. 원문은 이 요청을 분석하는 데만 쓰이며, 승인 전에는 파일에 저장되지 않습니다.</p><label htmlFor="project-statement">프로젝트 설명</label><textarea id="project-statement" value={statement} onChange={event => setStatement(event.target.value)} maxLength="1200" placeholder="목적, 대상, 원하는 결과를 편하게 적어 주세요." required /></> : <><p className="onboarding-notice">모드: {analysis.mode === 'llm-suggestion' ? 'AI 제안' : '로컬 초안'} · known facts, assumptions, unknowns를 구분한 편집 가능한 설계입니다.</p>{analysis.nextQuestion && clarifications.length < 2 && <div className="clarification"><p><b>확인 질문</b> {analysis.nextQuestion}</p><textarea value={answer} onChange={event => setAnswer(event.target.value)} maxLength="500" placeholder="답변을 입력한 뒤 재분석할 수 있습니다." /><button type="button" onClick={askAgain}>답변 추가 후 재분석</button></div>}<label htmlFor="blueprint">편집 가능한 blueprint JSON</label><textarea id="blueprint" value={blueprintText} onChange={event => setBlueprintText(event.target.value)} className="blueprint-editor" maxLength="8000" /><label htmlFor="member-id">member-id</label><input id="member-id" value={identity.memberId} onChange={event => setIdentity(current => ({ ...current, memberId: event.target.value }))} placeholder="lowercase-id" required /><label htmlFor="display-name">표시 이름</label><input id="display-name" value={identity.displayName} onChange={event => setIdentity(current => ({ ...current, displayName: event.target.value }))} required /><label htmlFor="working-context">승인할 개인 working context</label><textarea id="working-context" value={identity.workingContext} onChange={event => setIdentity(current => ({ ...current, workingContext: event.target.value }))} maxLength="360" placeholder="inferred profile 대신, 승인한 작업 맥락만 기록합니다." required /></>}{error && <p className="onboarding-error" role="alert">{error}</p>}<p className="onboarding-mode">{eventText(events)} 현재 저장 모드: <b>{serverState.persistenceMode === 'read-only-demo' ? '읽기 전용 배포' : '로컬 쓰기 가능'}</b></p><footer><button className="primary" type="submit" disabled={busy}>{busy ? '분석 중…' : analysis ? '파일 계획 미리보기' : 'Wiki 설계 제안 받기'}</button></footer></form></section>
}
